#ifndef TRANSPORTCLIENT_GLOBAL_H
#define TRANSPORTCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRANSPORTCLIENT_LIBRARY)
#  define TRANSPORTCLIENT_EXPORT Q_DECL_EXPORT
#else
#  define TRANSPORTCLIENT_EXPORT Q_DECL_IMPORT
#endif

#endif // TRANSPORTCLIENT_GLOBAL_H
